name: Atualizar CSV Pedidos

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '*/50 * * * *'

jobs:
  atualizar:
    runs-on: ubuntu-latest

    env:
      VTEX_ACCOUNT_NAME: ${{ secrets.VTEX_ACCOUNT_NAME }}
      VTEX_APP_KEY: ${{ secrets.VTEX_APP_KEY }}
      VTEX_APP_TOKEN: ${{ secrets.VTEX_APP_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Rodar script Itens VTEX
        run: python src/pedidos_itens.py

      - name: Rodar script Geral VTEX
        run: python src/pedidos_gerais.py

      - name: Commit CSV
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -f output/*.csv
          git commit -m "Atualiza CSVs VTEX" || echo "Sem alterações"
          git push
